### ISSUE TITLE
Update on nc-update to 22.2.2 from 22.0.0.11

### ISSUE THREAD

**Issue by lockeftw** [nextcloud/nextcloudpi#1388]
Thats the Ooutput from WUI by clicking on nc-update-nextcloud and then on apply:
_[ nc-update-nextcloud ] (Fri Nov 19 13:00:40 GMT 2021)
Current Nextcloud version 22.0.0.11
Available Nextcloud version 22.2.2
Download Nextcloud 22.2.2...
Back up current instance...
check free space...
Maintenance mode enabled
backup database...
backup files...
backup /var/www//nextcloud-bkp_20211119_1637326861.tar.gz generated
Maintenance mode disabled
Install Nextcloud 22.2.2...
Fix permissions...
Upgrade...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: cms_pico
Disabled incompatible app: contacts
Disabled incompatible app: cospend
Disabled incompatible app: files_accesscontrol
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: files_markdown
Disabled incompatible app: forms
Disabled incompatible app: health
Disabled incompatible app: integration_whiteboard
Disabled incompatible app: mail
Disabled incompatible app: maps
Disabled incompatible app: notes
Disabled incompatible app: notify_push
Disabled incompatible app: passwords
Disabled incompatible app: phonetrack
Disabled incompatible app: polls
Disabled incompatible app: spreed
Disabled incompatible app: talk_matterbridge
Disabled incompatible app: tasks
Disabled incompatible app: theming_customcss
Updating <federation> ...
Updated <federation> to 1.12.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.10.0
Updating <oauth2> ...
Updated <oauth2> to 1.10.0
Updating <files> ...
Updated <files> to 1.17.0
Updating <circles> ...

Upgrading Circles App

Starting ...
0/1 [>---------------------------] 0%
(Circles) Caching memberships for Members of 'admin'
1/1 [============================] 100%

Upgrading Circles App

Starting ...
0/0 [--->------------------------] 0%
Updated <circles> to 22.1.1
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.5.0
Updating <dav> ...
Fix broken values of calendar objects

Starting ...
0/0 [----->----------------------] 0%
Updated <dav> to 1.19.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.14.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.12.0
Updating <files_versions> ...
Updated <files_versions> to 1.15.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.12.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.4.0
Updating <comments> ...
Updated <comments> to 1.12.0
Updating <systemtags> ...
Updated <systemtags> to 1.12.0
Updating <theming> ...
Updated <theming> to 1.13.0
Updating <accessibility> ...
Migrate old user config

Starting ...
0/0 [------->--------------------] 0%
Updated <accessibility> to 1.8.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.3.0
Updating <dashboard> ...
Updated <dashboard> to 7.2.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.12.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.3.1
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.12.0
Updating <settings> ...
Updated <settings> to 1.4.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.11.0
Updating <user_status> ...
Updated <user_status> to 1.2.0
Updating <weather_status> ...
Updated <weather_status> to 1.2.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in App Store
Checking for update of app activity in appstore
Checked for update of app "activity" in App Store
Checking for update of app circles in appstore
Checked for update of app "circles" in App Store
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in App Store
Checking for update of app comments in appstore
Checked for update of app "comments" in App Store
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in App Store
Checking for update of app dashboard in appstore
Checked for update of app "dashboard" in App Store
Checking for update of app dav in appstore
Checked for update of app "dav" in App Store
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in App Store
Checking for update of app federation in appstore
Checked for update of app "federation" in App Store
Checking for update of app files in appstore
Checked for update of app "files" in App Store
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in App Store
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in App Store
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in App Store
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in App Store
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in App Store
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in App Store
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in App Store
Checking for update of app logreader in appstore
Checked for update of app "logreader" in App Store
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in App Store
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in App Store
Checking for update of app notifications in appstore
Checked for update of app "notifications" in App Store
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in App Store
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in App Store
Checking for update of app photos in appstore
Checked for update of app "photos" in App Store
Checking for update of app previewgenerator in appstore
Checked for update of app "previewgenerator" in App Store
Checking for update of app privacy in appstore
Checked for update of app "privacy" in App Store
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in App Store
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in App Store
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in App Store
Checking for update of app settings in appstore
Checked for update of app "settings" in App Store
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in App Store
Checking for update of app support in appstore
Checked for update of app "support" in App Store
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in App Store
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in App Store
Checking for update of app text in appstore
Checked for update of app "text" in App Store
Checking for update of app theming in appstore
Checked for update of app "theming" in App Store
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in App Store
Checking for update of app user_status in appstore
Checked for update of app "user_status" in App Store
Checking for update of app viewer in appstore
Checked for update of app "viewer" in App Store
Checking for update of app weather_status in appstore
Checked for update of app "weather_status" in App Store
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in App Store
Checking for update of app calendar in appstore
Checked for update of app "calendar" in App Store
Checking for update of app cms_pico in appstore
Checked for update of app "cms_pico" in App Store
Repair warning: Replacing Pico CMS config file "config.yml.template"
Repair warning: Replacing Pico CMS system template "empty"
Repair warning: Replacing Pico CMS system template "sample_pico"
Repair warning: Replacing Pico CMS system theme "default"
Repair warning: Replacing Pico CMS system plugin "PicoDeprecated"
Checking for update of app contacts in appstore
Checked for update of app "contacts" in App Store
Checking for update of app cospend in appstore
Checked for update of app "cospend" in App Store
Checking for update of app files_accesscontrol in appstore
Checked for update of app "files_accesscontrol" in App Store
Checking for update of app files_automatedtagging in appstore
Checked for update of app "files_automatedtagging" in App Store
Checking for update of app files_markdown in appstore
Checked for update of app "files_markdown" in App Store
Checking for update of app forms in appstore
Checked for update of app "forms" in App Store
Checking for update of app health in appstore
Checked for update of app "health" in App Store
Checking for update of app integration_whiteboard in appstore
Checked for update of app "integration_whiteboard" in App Store
Checking for update of app mail in appstore
Checked for update of app "mail" in App Store
Restore default tags that are missing

Starting ...
0/2 [>---------------------------] 0%
Starting ...
2/2 [============================] 100%
Purify and migrate collected mail addresses

Starting ...
0/0 [------------->--------------] 0%
Insert background jobs for all accounts

Starting ...
0/2 [>---------------------------] 0%
Starting ...
2/2 [============================] 100%
Checking for update of app maps in appstore
Checked for update of app "maps" in App Store
Checking for update of app notes in appstore
Checked for update of app "notes" in App Store
Checking for update of app notify_push in appstore
Checked for update of app "notify_push" in App Store
Checking for update of app passwords in appstore
Checked for update of app "passwords" in App Store
Checking for update of app phonetrack in appstore
Checked for update of app "phonetrack" in App Store
Checking for update of app polls in appstore
Checked for update of app "polls" in App Store
Checking for update of app spreed in appstore
Checked for update of app "spreed" in App Store
Checking for update of app talk_matterbridge in appstore
Checked for update of app "talk_matterbridge" in App Store
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.3-linux-32bit: Exec format error
Repair warning: Failed to read version from matterbridge binary
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.3-linux-32bit: Exec format error
Repair warning: Failed to read version from matterbridge binary
Checking for update of app tasks in appstore
Checked for update of app "tasks" in App Store
Checking for update of app theming_customcss in appstore
Checked for update of app "theming_customcss" in App Store
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Done.
Check columns of the comments table.
Done.
Check primary keys.
Done.
All tables already up to date!
Backup stored at /media/datapiccante/ncdata/ncp-update-backups/nextcloud-bkp_20211119_1637326861-22.0.0.11.tar.gz
Clean up..._

By Calling my Cloudurl it says previewGenerator has to be updated. So i clicked the Updatebutton and an error accures : 

### _Update vorbereiten

Log-Level auf "debug" gesetzt

Repair MySQL collation

All tables already have the correct collation -> nothing to do

Repair SQLite autoincrement

Copy data from accounts table when migrating from ownCloud

Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

InvalidArgumentException: Column "oc_preview_generation"."locked" is type Bool and also NotNull, so it can not store "false"._

Then i tried to upgrade the preview generator via terminal by using:
`sudo -u www-data occ upgrade`

the output was:

`
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <previewgenerator> ...
InvalidArgumentException: Column "oc_preview_generation"."locked" is type Bool and also NotNull, so it can not store "false".
Update failed
Maintenance mode is kept active
Resetting log level`

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.44.3
NextCloudPi image    NextCloudPi_03-28-20
OS                   Raspbian GNU/Linux 10. 5.10.63-v7l+ (armv7l)
automount            yes
USB devices          sda sdb
datadir              /media/datapiccante/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      791G/3.7T
rootfs usage         3.5G/59G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    22.2.2.0
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          down
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               3days

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "11": "2003:e2:2f31:5000:7b8c:3e29:8579:6f26",
            "1": "192.168.178.31",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "12": "cloud.datapiccante.de",
            "": "cloud.datapiccante.de"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.2.0",
        "overwrite.cli.url": "https:\/\/cloud.datapiccante.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/datapiccante\/ncdata\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "maintenance": true,
        "logfile": "\/media\/datapiccante\/ncdata\/nextcloud.log",
        "mail_sendmailmode": "smtp",
        "htaccess.RewriteBase": "\/",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "loglevel": "2",
        "data-fingerprint": "ad9fca1f3ec533b093e7e469b0753e94",
        "theme": "",
        "updater.release.channel": "stable",
        "log_type": "file",
        "app_install_overwrite": [
            "passwords",
            "tasks",
            "previewgenerator",
            "forms"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Fri Nov 19 00:00:05.784920 2021] [ssl:warn] [pid 1398:tid 3070022208] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Fri Nov 19 00:00:05.793586 2021] [mpm_event:notice] [pid 1398:tid 3070022208] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Fri Nov 19 00:00:05.793631 2021] [core:notice] [pid 1398:tid 3070022208] AH00094: Command line: '/usr/sbin/apache2'
[Fri Nov 19 01:59:55.346221 2021] [core:error] [pid 24512:tid 2602497024] [client 45.146.164.110:32938] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Fri Nov 19 12:59:49.687949 2021] [proxy_fcgi:error] [pid 24511:tid 2831283200] [client 192.168.178.61:50215] AH01071: Got error 'PHP message: PHP Notice:  Undefined property: L10N::$__ in /var/www/ncp-web/index.php on line 221'
[Fri Nov 19 13:17:17.022619 2021] [proxy_fcgi:error] [pid 24511:tid 2965566464] [client 192.168.178.61:50215] AH01067: Failed to read FastCGI header
[Fri Nov 19 13:17:17.025468 2021] [proxy_fcgi:error] [pid 24511:tid 2965566464] (104)Connection reset by peer: [client 192.168.178.61:50215] AH01075: Error dispatching request to :4443:
[Fri Nov 19 13:22:27.030843 2021] [proxy_fcgi:error] [pid 24512:tid 3024315392] [client 192.168.178.61:50291] AH01067: Failed to read FastCGI header
[Fri Nov 19 13:22:27.030943 2021] [proxy_fcgi:error] [pid 24512:tid 3024315392] (104)Connection reset by peer: [client 192.168.178.61:50291] AH01075: Error dispatching request to :4443:

```
</details>

<details>
<summary>Database logs</summary>

```


```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::info: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: All tables already have the correct collation -> nothing to do","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:28+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":0,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"cms_pico","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":0,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"files_sharing","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":0,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"maps","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:29+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <previewgenerator> ...","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":3,"time":"2021-11-19T13:21:31+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Column \"oc_preview_generation\".\"locked\" is type Bool and also NotNull, so it can not store \"false\".","userAgent":"--","version":"22.2.2.0","exception":{"Exception":"InvalidArgumentException","Message":"Column \"oc_preview_generation\".\"locked\" is type Bool and also NotNull, so it can not store \"false\".","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/DB/MigrationService.php","line":538,"function":"ensureOracleConstraints","class":"OC\\DB\\MigrationService","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"},{"__class__":"Doctrine\\DBAL\\Schema\\Schema"},3]},{"file":"/var/www/nextcloud/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->","args":["020200Date20190608205303",false]},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":1010,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":352,"function":"updateApp","class":"OC_App","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":264,"function":"doAppUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":132,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["22.2.2.0","22.2.2.0"]},{"file":"/var/www/nextcloud/core/Command/Upgrade.php","line":241,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\Upgrade"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":209,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/console.php","line":99,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/DB/MigrationService.php","Line":595,"CustomMessage":"Column \"oc_preview_generation\".\"locked\" is type Bool and also NotNull, so it can not store \"false\"."}}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":3,"time":"2021-11-19T13:21:31+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::failure: InvalidArgumentException: Column \"oc_preview_generation\".\"locked\" is type Bool and also NotNull, so it can not store \"false\".","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":3,"time":"2021-11-19T13:21:31+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:31+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"22.2.2.0"}
{"reqId":"0fPvm8iaiBuKw5hjXE0R","level":1,"time":"2021-11-19T13:21:31+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"22.2.2.0"}

```
</details>

[ nc-update-nextcloud ] (Fri Nov 19 13:00:40 GMT 2021)
Current Nextcloud version 22.0.0.11
Available Nextcloud version 22.2.2
Download Nextcloud 22.2.2...
Back up current instance...
check free space...
Maintenance mode enabled
backup database...
backup files...
backup /var/www//nextcloud-bkp_20211119_1637326861.tar.gz generated
Maintenance mode disabled
Install Nextcloud 22.2.2...
Fix permissions...
Upgrade...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: cms_pico
Disabled incompatible app: contacts
Disabled incompatible app: cospend
Disabled incompatible app: files_accesscontrol
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: files_markdown
Disabled incompatible app: forms
Disabled incompatible app: health
Disabled incompatible app: integration_whiteboard
Disabled incompatible app: mail
Disabled incompatible app: maps
Disabled incompatible app: notes
Disabled incompatible app: notify_push
Disabled incompatible app: passwords
Disabled incompatible app: phonetrack
Disabled incompatible app: polls
Disabled incompatible app: spreed
Disabled incompatible app: talk_matterbridge
Disabled incompatible app: tasks
Disabled incompatible app: theming_customcss
Updating <federation> ...
Updated <federation> to 1.12.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.10.0
Updating <oauth2> ...
Updated <oauth2> to 1.10.0
Updating <files> ...
Updated <files> to 1.17.0
Updating <circles> ...

Upgrading Circles App

Starting ...
0/1 [>---------------------------] 0%
(Circles) Caching memberships for Members of 'admin'
1/1 [============================] 100%

Upgrading Circles App

Starting ...
0/0 [--->------------------------] 0%
Updated <circles> to 22.1.1
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.5.0
Updating <dav> ...
Fix broken values of calendar objects

Starting ...
0/0 [----->----------------------] 0%
Updated <dav> to 1.19.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.14.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.12.0
Updating <files_versions> ...
Updated <files_versions> to 1.15.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.12.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.4.0
Updating <comments> ...
Updated <comments> to 1.12.0
Updating <systemtags> ...
Updated <systemtags> to 1.12.0
Updating <theming> ...
Updated <theming> to 1.13.0
Updating <accessibility> ...
Migrate old user config

Starting ...
0/0 [------->--------------------] 0%
Updated <accessibility> to 1.8.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.3.0
Updating <dashboard> ...
Updated <dashboard> to 7.2.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.12.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.3.1
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.12.0
Updating <settings> ...
Updated <settings> to 1.4.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.11.0
Updating <user_status> ...
Updated <user_status> to 1.2.0
Updating <weather_status> ...
Updated <weather_status> to 1.2.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in App Store
Checking for update of app activity in appstore
Checked for update of app "activity" in App Store
Checking for update of app circles in appstore
Checked for update of app "circles" in App Store
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in App Store
Checking for update of app comments in appstore
Checked for update of app "comments" in App Store
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in App Store
Checking for update of app dashboard in appstore
Checked for update of app "dashboard" in App Store
Checking for update of app dav in appstore
Checked for update of app "dav" in App Store
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in App Store
Checking for update of app federation in appstore
Checked for update of app "federation" in App Store
Checking for update of app files in appstore
Checked for update of app "files" in App Store
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in App Store
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in App Store
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in App Store
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in App Store
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in App Store
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in App Store
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in App Store
Checking for update of app logreader in appstore
Checked for update of app "logreader" in App Store
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in App Store
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in App Store
Checking for update of app notifications in appstore
Checked for update of app "notifications" in App Store
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in App Store
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in App Store
Checking for update of app photos in appstore
Checked for update of app "photos" in App Store
Checking for update of app previewgenerator in appstore
Checked for update of app "previewgenerator" in App Store
Checking for update of app privacy in appstore
Checked for update of app "privacy" in App Store
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in App Store
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in App Store
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in App Store
Checking for update of app settings in appstore
Checked for update of app "settings" in App Store
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in App Store
Checking for update of app support in appstore
Checked for update of app "support" in App Store
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in App Store
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in App Store
Checking for update of app text in appstore
Checked for update of app "text" in App Store
Checking for update of app theming in appstore
Checked for update of app "theming" in App Store
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in App Store
Checking for update of app user_status in appstore
Checked for update of app "user_status" in App Store
Checking for update of app viewer in appstore
Checked for update of app "viewer" in App Store
Checking for update of app weather_status in appstore
Checked for update of app "weather_status" in App Store
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in App Store
Checking for update of app calendar in appstore
Checked for update of app "calendar" in App Store
Checking for update of app cms_pico in appstore
Checked for update of app "cms_pico" in App Store
Repair warning: Replacing Pico CMS config file "config.yml.template"
Repair warning: Replacing Pico CMS system template "empty"
Repair warning: Replacing Pico CMS system template "sample_pico"
Repair warning: Replacing Pico CMS system theme "default"
Repair warning: Replacing Pico CMS system plugin "PicoDeprecated"
Checking for update of app contacts in appstore
Checked for update of app "contacts" in App Store
Checking for update of app cospend in appstore
Checked for update of app "cospend" in App Store
Checking for update of app files_accesscontrol in appstore
Checked for update of app "files_accesscontrol" in App Store
Checking for update of app files_automatedtagging in appstore
Checked for update of app "files_automatedtagging" in App Store
Checking for update of app files_markdown in appstore
Checked for update of app "files_markdown" in App Store
Checking for update of app forms in appstore
Checked for update of app "forms" in App Store
Checking for update of app health in appstore
Checked for update of app "health" in App Store
Checking for update of app integration_whiteboard in appstore
Checked for update of app "integration_whiteboard" in App Store
Checking for update of app mail in appstore
Checked for update of app "mail" in App Store
Restore default tags that are missing

Starting ...
0/2 [>---------------------------] 0%
Starting ...
2/2 [============================] 100%
Purify and migrate collected mail addresses

Starting ...
0/0 [------------->--------------] 0%
Insert background jobs for all accounts

Starting ...
0/2 [>---------------------------] 0%
Starting ...
2/2 [============================] 100%
Checking for update of app maps in appstore
Checked for update of app "maps" in App Store
Checking for update of app notes in appstore
Checked for update of app "notes" in App Store
Checking for update of app notify_push in appstore
Checked for update of app "notify_push" in App Store
Checking for update of app passwords in appstore
Checked for update of app "passwords" in App Store
Checking for update of app phonetrack in appstore
Checked for update of app "phonetrack" in App Store
Checking for update of app polls in appstore
Checked for update of app "polls" in App Store
Checking for update of app spreed in appstore
Checked for update of app "spreed" in App Store
Checking for update of app talk_matterbridge in appstore
Checked for update of app "talk_matterbridge" in App Store
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.3-linux-32bit: Exec format error
Repair warning: Failed to read version from matterbridge binary
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.3-linux-32bit: Exec format error
Repair warning: Failed to read version from matterbridge binary
Checking for update of app tasks in appstore
Checked for update of app "tasks" in App Store
Checking for update of app theming_customcss in appstore
Checked for update of app "theming_customcss" in App Store
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Done.
Check columns of the comments table.
Done.
Check primary keys.
Done.
All tables already up to date!
Backup stored at /media/datapiccante/ncdata/ncp-update-backups/nextcloud-bkp_20211119_1637326861-22.0.0.11.tar.gz
Clean up...

**Comment by CarlosCastaneda** [comment]
There very same to me:

 sudo /usr/local/bin/ncc upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <previewgenerator> ...
InvalidArgumentException: Column "oc_preview_generation"."locked" is type Bool and also NotNull, so it can not store "false".
Update failed
Maintenance mode is kept active
Resetting log level

**Comment by dyraig** [comment]
I just ran into the same issue while running the curl-installer on a freshly installed Raspberry Pi 2 with Raspbian Buster:
[...]
Thanks for using MariaDB!
Installing nc-nextcloud
Running nc-nextcloud
Downloading Nextcloud 22.2.2...
Installing  Nextcloud 22.2.2...
Creating possible missing Directories
chmod Files and Directories
chown Directories
chmod/chown .htaccess
Setting up database...
Setting up Apache...
[...]
asks 0.14.2 installed
tasks enabled
tasks already enabled
updatenotification 1.12.0 disabled
notify_push 0.3.0 installed
notify_push enabled
notify_push already enabled
Column "oc_preview_generation"."locked" is type Bool and also NotNull, so it can not store "false".

**Comment by nachoparker** [comment]
should be fixed in the latest version. Otherwise please use the forums for support, you can add a link here to the forum post even after I close it.

Thanks

**Comment by daniel1v** [comment]
@nachoparker, it seems like the issues persists for several users. the only way to get around this, is to (permanently) disable the preview genearator.
