### ISSUE TITLE
Broken link on NC forum

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/nextcloudpi#1491]
On that page:
[https://help.nextcloud.com/t/about-the-nextcloudpi-documentation-category/125977](https://help.nextcloud.com/t/about-the-nextcloudpi-documentation-category/125977)

The link to the **Installation Guide** does not work although i am logged in to the forum:

_If this is your first time with NextCloudPi, start with the [Installation Guide](https://help.nextcloud.com/t/welcome-to-ncp-wiki/126323)_

![Seite nicht gefunden - Nextcloud community - Google Chrome_001](https://user-images.githubusercontent.com/24833757/174876842-e27317bc-d156-4b1a-8599-57ac44e14760.png)

I found one here, too:

![GitHub - nextcloud-nextcloudpi: 📦 Build code for NextcloudPi: Raspberry Pi, Odroid, Rock64, Docker, curl installer  - Google Chrome_001](https://user-images.githubusercontent.com/24833757/174878318-066b60cd-c6b7-4185-a59c-0bdd36cc3a0d.png)

**Comment by schoetju** [comment]
Seems to be fixed meanwhile, see
https://help.nextcloud.com/t/about-the-nextcloudpi-documentation-category/125977/3

**Comment by Jeanoo** [comment]
does not work yet the links are not clickable 

https://help.nextcloud.com/t/index-nextcloudpi-documentation/126448

**Comment by schoetju** [comment]
Please try again - i've reached out to NCP Wiki Team via Matrix-Chat and it's fixed now (at least as i can see from my end)

**Comment by Jeanoo** [comment]
still not possible:
The links do not work or contain incorrect information from "Installation".

**Comment by schoetju** [comment]
Please try again - at least the "installation"-links are fixed now. Rest of the index-page will be done soon...

**Comment by Jeanoo** [comment]
the "installation" links are now working thanks
but not the rest 
Update
Backup & Restore
...

**Comment by theCalcaholic** [comment]
I received feedback from the Wiki team that this issue should be resolved now. If you still encounter problems, feel free to comment and I'll open it again

**Comment by Jeanoo** [comment]
from "Configure".
the links do not work

**Comment by theCalcaholic** [comment]
@Jeanoo I believe that's because the pages aren't finished yet

**Comment by sunjam** [comment]
@Jeanoo do you mind reporting these issues on the forum itself.  We are not actively monitoring github for forum issues.

On documentation reported here... you could assign a specific tag such as `documentation` @theCalcaholic that we could monitor from the wiki team matrix chat room rss bot.  [Details here](https://vilcins.medium.com/rss-feeds-for-your-github-releases-tags-and-activity-cbda2c51373) in case this makes it easier to auto-notify the volunteers of documentation requests posted to Github.  Your call.

```
/* Repo tags */

https://github.com/:user/:repo/tags.atom
```

**Comment by sunjam** [comment]
@Jeanoo You can join [our group](https://help.nextcloud.com/g/NCP_Wiki_Team/) directly on the forum to help us fix draft and incomplete documentation directly.  This will at least show you all possible documentation as opposed to broken links.

https://help.nextcloud.com/g/NCP_Wiki_Team/

**Comment by theCalcaholic** [comment]
@sunjam That's a very good idea :)
