### ISSUE TITLE
bug...I can't close SSH in ncp-web....

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/nextcloudpi#466]
bug...I can't close SSH in nextcloudpi-web....
If I want to close, I must turn off from raspi-config

**Comment by nachoparker** [comment]
do you mean that you can't disable SSH from ncp-web?

**Comment by chiyi4488** [comment]
yes!

**Comment by nachoparker** [comment]
do you get any error? do you get the red ball on ncp-web?

**Comment by chiyi4488** [comment]
No, I get green ball

**Comment by nachoparker** [comment]
so everything seems ok, but you can still connect through SSH?

**Comment by chiyi4488** [comment]
Yes, if I really want to close, I must turn off from raspi-config.

**Comment by nachoparker** [comment]
I see... you are right. SSH is disabled, but not stopped right away.

Fixed in `v0.53.8`.

Thanks for your feedback!

**Comment by ZJaume** [comment]
The bug persists for me on 0.58.1, I click run and the ncp-web ignores that "ACTIVATE" option is disabled and sets the password and enables the service again.

**Comment by chiyi4488** [comment]
Why? I can close.
